Add driver_colors function for easier plotting of lines from same team drivers
theOehrly/Fast-F1 pull request #159
Opened 2022-04-22 20:23 UTC by dialtone

Pull request from this discussion https://github.com/theOehrly/Fast-F1/discussions/145

2022-04-26 13:29 UTC, theOehrly commented
Hi, just so that you don't sit here wondering, I'll try to take a closer look at this today or tomorrow, hopefully.

2022-04-27 21:13 UTC, theOehrly requested changes
Just some minor details. Also, please fix the lint failure.

2022-04-27 21:13 UTC, theOehrly commented on fastf1/plotting.py
> +        shortened driver names, included sponsors and typos can be dealt with
remove the sponsors part, not applicable here

2022-04-27 21:13 UTC, theOehrly commented on fastf1/plotting.py
> +        identifier (str): Abbreviation or uniquely identifying name of the team.
driver, not team; 
see comments in code below too

2022-04-27 21:19 UTC, theOehrly commented
Everything else looks good. I have also thought about the plain white Haas color again. We had discussed this shortly in #145. I'd say it's fine for now. Team colors are that way too and it works with FastF1s usual dark theme. Support for switching between light and dark theme should be added separately, and this should then include two separate color pallets. But this is a separate problem.

2022-04-27 22:03 UTC, theOehrly commented
These two should be fixed so that ci passes cleanly

```
=================================== FAILURES ===================================
_________________________________ FLAKE8-check _________________________________
/home/runner/work/Fast-F1/Fast-F1/fastf1/plotting.py:190:1: E302 expected 2 blank lines, found 1
/home/runner/work/Fast-F1/Fast-F1/fastf1/plotting.py:256:1: E302 expected 2 blank lines, found 1
```

2022-04-27 23:32 UTC, dialtone commented
I think I fixed the 2 CI errors.

2022-04-28 19:44 UTC, theOehrly approved these changes

2022-04-28 19:49 UTC, merged

2022-04-28 19:50 UTC, theOehrly commented
Yes, looks all good now. Thanks a lot for contributing!

2022-04-28 19:51 UTC, dialtone commented
my pleasure, thanks for the library in the first place