Draft: Solution for #196: Optional strict_search parameter for get_event to avoid incorrect results
theOehrly/Fast-F1 pull request #285
Opened 2022-11-07 21:37 UTC by Neron-png

When using the get_event() function there's now the option to set `strict_search`  argument to only return an event if it's name matches the query, returning None otherwise.

`get_event(year, gp, *, force_ergast=False, strict_search=False)`

This is a non-breaking change; `strict_search` is pre-set to False, allowing past code written using Fastf1 to continue working in the exact same fashion.
Relevant documentation updated as well

2022-11-10 13:01 UTC, theOehrly requested changes
Hi, thank you for your interest in contributing to FastF1. Overall, this is a nice little enhancement. I'd only like you to make some minor changes as I have noted. 
Also, the doc build is likely failing because of formatting error in one of the changed docstrings. Please fix that.
```
/home/runner/work/Fast-F1/Fast-F1/fastf1/events.py:docstring of fastf1.events.EventSchedule.get_event_by_name:26: ERROR: Unexpected indentation.

/home/runner/work/Fast-F1/Fast-F1/fastf1/events.py:docstring of fastf1.events.EventSchedule.get_event_by_name:28: WARNING: Field list ends without a blank line; unexpected unindent.
```

2022-11-10 15:07 UTC, Neron-png commented
> Hi, thank you for your interest in contributing to FastF1. Overall, this is a nice little enhancement. I'd only like you to make some minor changes as I have noted. 

Hi, thanks for your feedback, I'll attend to the changes as soon as I can!

2022-11-13 21:44 UTC, Neron-png commented
Still a bit lost with Sphinx,
Probably it's still got to do with this
`/home/runner/work/Fast-F1/Fast-F1/fastf1/events.py:docstring of fastf1.events.EventSchedule.get_event_by_name:28: WARNING: Field list ends without a blank line; unexpected unindent.`

2022-11-13 22:17 UTC, Neron-png commented
Should be now covering the changes & failing docs, finally found out how to test the builds locally 😅
Thanks for the patience

2022-11-14 10:55 UTC, theOehrly commented
This looks good now. Thank you very much for contributing!

2022-11-14 10:56 UTC, merged