Added some type hinting
theOehrly/Fast-F1 pull request #287
Opened 2022-11-14 18:04 UTC by BCurbs

I added a bunch of type hinting, and then tried to fix flake8, but it looks like it was already messed up so I'm submitting as is. 
Should go a long way to fixing #286

2022-11-14 18:50 UTC, theOehrly commented
Thank you for submitting this PR. I haven't reviewed this properly yet. I'll try to get around to it soon.
Regarding flake8, line length compliance is only enforced for changed lines. Thereby, FastF1 should slowly transition to full compliance with that guideline. You don't need to fix that except on lines that you modify anyways.

2022-11-17 16:27 UTC, theOehrly commented
@BCurbs in general, I'm happy with these changes. Before I review in detail, please check the docs for how to run the tests and lint checks locally. This will make it much easier to get the CI to pass.

2022-11-22 17:06 UTC, theOehrly requested changes
I finally got around to taking a proper look at this. 

Some things that need to be done still:
- lint failure: the flake8 check needs to pass. You can also run this locally. Check the docs to see how
- When type hints are present, no type information should be given in docstrings. Therefore, you should remove the type information from all docstrings where type hints have been added
- I've added some more specific notes as review comments

2022-11-23 17:51 UTC, BCurbs commented on fastf1/core.py
> +        # calculate "driver ahead from" from data without padding to
My IDE got real angry with me for a grammar error before.

2022-12-03 08:16 UTC, theOehrly commented
@BCurbs just FYI, I haven't forgotten about this. I'm just really busy right now with other things. Hopefully I'll get around to looking at your PR again somewhere next week.

2022-12-13 22:03 UTC, theOehrly requested changes
Hey, finally I got around to this again. Mostly everything looks good. I've added a few comments, nothing major. Especially in core.py there are a few methods where you have added type hints to the arguments or as return type but not removed the information from the docstring. I guess you just missed those, because, for example, in events.py this is correct.

2022-12-13 22:08 UTC, theOehrly commented
One more thing, please merge with master, because I needed to fix the flake8 CI test. Else it won't work here.

2022-12-14 19:28 UTC, BCurbs commented
The email associated with the commits has switched to a different github account, which is going to be my primary  account after this pull request is complete. Other than that, I think I have everything fixed.

2022-12-15 22:25 UTC, theOehrly commented on fastf1/events.py
> +from datetime import datetime
This causes the test failure. You should not change that import

2022-12-15 22:25 UTC, theOehrly commented on fastf1/events.py
> +        dt: Optional[datetime] = None, *, include_testing: bool = True,
use Optional[datetime.datetime] here instead

2022-12-15 22:27 UTC, theOehrly commented
It'll be easier for you to catch these errors if you set up the tests to run locally. Especially because I need to approve each CI run here as you are a first-time contributor to this repository,
See https://theoehrly.github.io/Fast-F1/contributing/index.html

2023-01-09 13:42 UTC, BCurbs commented
Yep, you're good to push your changes.

2023-01-10 11:06 UTC, merged

2023-01-10 11:08 UTC, theOehrly commented
Thank you very much for all your work on this PR!

2023-01-10 14:23 UTC, transorsmth commented
Thank you for your review, I haven't worked with any of these things like dataframes or anything in this structure yet, so thanks for putting up with me.

2023-01-11 09:35 UTC, theOehrly commented
> Thank you for your review, I haven't worked with any of these things like dataframes or anything in this structure yet, so thanks for putting up with me.

No worries, with changes throughout the project, this was not necessarily a simple PR. Also, my aim for this project is to encourage more contributions. And reviewing PRs is an interesting challenge and learning opportunity for myself, as I am fairly new to that.