Improve support for Sprint Shootout format
theOehrly/Fast-F1 pull request #363
Opened 2023-05-05 22:05 UTC by mdsakalu

- Defined session tuples for "race-like" (saw this nomenclature in the docs in a few spots) and "quali-like" sessions which cleans up places where those groupings of sessions are used.
- Updated docs to add `Sprint Shootout` where appropriate.
- Added `_calculate_quali_like_session_results` method to calculate quali and sprint shootout results from laps.
- Used `_calculate_quali_like_session_results` to calculate sprint shootout results since Ergast doesn't support that format yet.
- Added some logic to support `sprint_shootout` event format when loading the schedule. Ergast doesn't support it yet, so for now assuming any sprint race for 2023 should use `sprint_shootout` format.
- Added/updated some tests with sprint shootout scenarios.

2023-05-05 22:09 UTC, mdsakalu commented on fastf1/core.py
> +            elif row['Status'] == 'Finished':
This handles the case when a qualifying session isn't restarted after a red flag

2023-05-07 17:01 UTC, theOehrly requested changes

2023-05-07 17:05 UTC, theOehrly commented
Hi, thank you for this contribution. This is very well implemented, tested and documented already. I only have some minor notes that you should address, please.

The remaining CI failure is currently expected and unrelated. You can ignore that.

2023-05-08 01:49 UTC, mdsakalu commented
Everything should be fixed now

2023-05-08 09:47 UTC, theOehrly approved these changes
Everything looks good now

2023-05-08 16:44 UTC, theOehrly commented
I'll merge this as it is. The remaining CI failures are caused by some general problems with the test runs that I'm currently fixing. So they are unrelated.

Thank you very much for your work on this PR!

2023-05-08 16:45 UTC, merged