Strategy example
theOehrly/Fast-F1 pull request #372
Opened 2023-05-12 01:37 UTC by Casper-Guo

File running correctly also depends on #368. The following plot is generated:
![test](https://github.com/theOehrly/Fast-F1/assets/89810860/ddea8920-027f-4fc9-9325-dc9aa315c97a)

Note that the drivers ideally will appear in descending order by finishing position. This is the behaviour seen in similar functions in the past. Some basic investigation shows that the drivers do not appear in `session.laps` in sorted finishing order. This may be a bug.

2023-05-12 13:15 UTC, Casper-Guo commented
P.S Doc build check failure is fixed by #368

2023-05-12 14:04 UTC, theOehrly commented
I merged #368, please rebase onto master again.

2023-05-14 20:17 UTC, MooshuBeef commented
I tried running the code and got this. I should have the latest on python, matplotlib, and seaborn

[Error from plot_driver_laptimes.txt](https://github.com/theOehrly/Fast-F1/files/11472851/Error.from.plot_driver_laptimes.txt)

2023-05-14 20:45 UTC, theOehrly commented
> I tried running the code and got this. I should have the latest on python, matplotlib, and seaborn
> [...]

This is a bug in FastF1 that was fixed by the PR that we talked above already (#368).

2023-05-14 21:44 UTC, MooshuBeef commented
Ahhh I see thank you!

2023-05-16 17:24 UTC, theOehrly requested changes
Mostly the same comments as on the other PR. I made the comments a bit shorter here, no intention to be rude 😅

2023-05-16 17:24 UTC, theOehrly commented on examples/plot_strategy.py
> +
Defer figures after every block. Or in this case, just create the figure later as well.

2023-05-16 17:24 UTC, theOehrly commented on examples/plot_strategy.py
> +# We need to find the stint length and compound used
All comment sentences with '.' at the end

2023-05-19 21:34 UTC, theOehrly approved these changes

2023-05-19 21:35 UTC, theOehrly commented
Looks good as well. Thank you for adding these three very helpful examples!

(And I'll get around to your other open PR and discussions soon now.)

2023-05-19 21:36 UTC, merged

2023-05-19 21:52 UTC, Casper-Guo commented
You are welcome! Being able to contribute to a project that I use a ton really is a joy.

I will try to work on some of the visuals in #325 in the future; there are several that I want to learn to make. In the meantime, I am more than glad to investigate any other good visualizations you find as well

2023-05-19 21:57 UTC, Casper-Guo commented
For this particular plot, I also make a more complex version to highlight SC and VSC periods and provide additional context. Those code can be used for a track status overview (like the following) if you think that's something people will be interested in:

![image](https://github.com/theOehrly/Fast-F1/assets/89810860/1fe4204e-5330-481f-8b92-ca2266620ac6)

2023-05-22 16:22 UTC, theOehrly commented
> For this particular plot, I also make a more complex version to highlight SC and VSC periods and provide additional context. Those code can be used for a track status overview (like the following) if you think that's something people will be interested in:
> 
> ![image](https://user-images.githubusercontent.com/89810860/239645919-1fe4204e-5330-481f-8b92-ca2266620ac6.png)

I think something like this would be cool as well. There's no example yet, that really utilizes this information. So it's nice to show that this data is available.